export const BUNDLE_BOOKING_STATUS = {
  PENDING_SUPPLIER_APPROVAL: "pending_supplier_approval",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
  IN_PROGRESS: "in_progress",
  DONE: "done",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
} as const;

export type BundleBookingStatus =
  (typeof BUNDLE_BOOKING_STATUS)[keyof typeof BUNDLE_BOOKING_STATUS];

export const BUNDLE_BOOKING_CANCELLED_BY = {
  CUSTOMER: "customer",
  SUPPLIER: "supplier",
} as const;

export type BundleBookingCancelledBy =
  (typeof BUNDLE_BOOKING_CANCELLED_BY)[keyof typeof BUNDLE_BOOKING_CANCELLED_BY];

export const BUNDLE_BOOKING_TERMINAL_STATUSES = [
  BUNDLE_BOOKING_STATUS.COMPLETED,
  BUNDLE_BOOKING_STATUS.CANCELLED,
  BUNDLE_BOOKING_STATUS.REJECTED,
] as const;

export const BUNDLE_BOOKING_ACTIVE_SLOT_STATUSES = [
  BUNDLE_BOOKING_STATUS.PENDING_SUPPLIER_APPROVAL,
  BUNDLE_BOOKING_STATUS.ACCEPTED,
  BUNDLE_BOOKING_STATUS.IN_PROGRESS,
  BUNDLE_BOOKING_STATUS.DONE,
] as const;

export const BUNDLE_BOOKING_TRANSITIONS: Record<BundleBookingStatus, BundleBookingStatus[]> = {
  [BUNDLE_BOOKING_STATUS.PENDING_SUPPLIER_APPROVAL]: [
    BUNDLE_BOOKING_STATUS.ACCEPTED,
    BUNDLE_BOOKING_STATUS.REJECTED,
    BUNDLE_BOOKING_STATUS.CANCELLED,
  ],
  [BUNDLE_BOOKING_STATUS.ACCEPTED]: [
    BUNDLE_BOOKING_STATUS.IN_PROGRESS,
    BUNDLE_BOOKING_STATUS.CANCELLED,
  ],
  [BUNDLE_BOOKING_STATUS.IN_PROGRESS]: [
    BUNDLE_BOOKING_STATUS.DONE,
    BUNDLE_BOOKING_STATUS.CANCELLED,
  ],
  [BUNDLE_BOOKING_STATUS.DONE]: [
    BUNDLE_BOOKING_STATUS.COMPLETED,
    BUNDLE_BOOKING_STATUS.CANCELLED,
  ],
  [BUNDLE_BOOKING_STATUS.COMPLETED]: [],
  [BUNDLE_BOOKING_STATUS.CANCELLED]: [],
  [BUNDLE_BOOKING_STATUS.REJECTED]: [],
};

export const BUNDLE_BOOKING_NOTIFICATION_TYPES = {
  CREATED: "BUNDLE_BOOKING_CREATED",
  ACCEPTED: "BUNDLE_BOOKING_ACCEPTED",
  REJECTED: "BUNDLE_BOOKING_REJECTED",
  DONE: "BUNDLE_BOOKING_DONE",
  COMPLETED: "BUNDLE_BOOKING_COMPLETED",
  CANCELLED: "BUNDLE_BOOKING_CANCELLED",
} as const;
