export const CATEGORY_QUEUE_EVENTS = {
  CREATED: "CATEGORY_CREATED",
  UPDATED: "CATEGORY_UPDATED",
  DELETED: "CATEGORY_DELETED",
  ACTIVATED: "CATEGORY_ACTIVATED",
  DEACTIVATED: "CATEGORY_DEACTIVATED",
} as const;