export const GOVERNMENT_QUEUE_EVENTS = {
  CREATED: "GOVERNMENT_CREATED",
  UPDATED: "GOVERNMENT_UPDATED",
  DEACTIVATED: "GOVERNMENT_DEACTIVATED",
  ACTIVATED: "GOVERNMENT_ACTIVATED",
  TOGGLED: "GOVERNMENT_TOGGLED",
} as const;
